### ISSUE TITLE
Vue dev proxy should use NS account number from .env

### ISSUE THREAD

**Issue by michoelchaikin** [finitydevs/create-spa-netsuite#8]
The vue devServer proxy is currently hardcoded in "client/vue.config.js" to the NetSuite account that was specified when the project was initialised.

This means that if you want to later change the NetSuite account you are developing against you have to change it in multiple places (.env files as well as vue.config.js). Additionally, the account number may be considered sensitive and shouldn't be committed to source control.

The vue config file should rather read this from the .env.

See this commit to my netsuite-mapreduce-util with the changes required.

https://github.com/michoelchaikin/netsuite-mapreduce-util/commit/01f5cf2b378e176e66123b2f178186b987ea3173

**Comment by mayerlench** [comment]
Thanks. I fixed this and it will be released in beta 8
